project_id = "zsrsfzlmspmjjnwopefd"

[api]
enabled = true

[functions.ai-chat]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.search-retreats]
verify_jwt = false

[functions.stripe-create-checkout]
verify_jwt = false

[functions.stripe-verify-retreat-payment]
verify_jwt = false
